version: 1.0.{build}
configuration: Release

install:
  - ps: git show --quiet --pretty=tformat:%s $env.APPVEYOR_REPO_COMMIT
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -fsS -o testspace-windows.zip https://testspace-client.s3.amazonaws.com/testspace-windows-dev.zip
  - 7z x -y testspace-windows.zip
  - testspace config url http://095d8acfaaf71b4a0f3767e41152620ebdda1b31@mark.stridespace.com
  

# to run your custom scripts instead of automatic MSBuild
build_script:
  - echo This is my custom build script
  - set > printenv.txt

# to run your custom scripts instead of automatic tests
test_script:
  - echo This is my custom test script
  
after_test:
  - testspace test.xml "+printenv.txt{environment variables}" 
